-- =============================================================================
-- WTI Trading Bot - Initial Database Schema
-- =============================================================================
-- This script creates the core database schema for the WTI trading bot.
-- It includes tables for market data, signals, orders, positions, and risk events.
-- =============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements";

-- Try to enable TimescaleDB if available (optional)
DO $$
BEGIN
    CREATE EXTENSION IF NOT EXISTS "timescaledb";
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'TimescaleDB not available, using standard PostgreSQL';
END $$;

-- =============================================================================
-- Core Tables
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Market Data Tables
-- -----------------------------------------------------------------------------

-- Raw tick data (price updates)
CREATE TABLE IF NOT EXISTS ticks (
    id BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    bid_price DECIMAL(18, 8),
    ask_price DECIMAL(18, 8),
    last_price DECIMAL(18, 8) NOT NULL,
    bid_size BIGINT,
    ask_size BIGINT,
    last_size BIGINT,
    volume BIGINT,
    exchange VARCHAR(20),
    feed_source VARCHAR(50) NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed_at TIMESTAMPTZ,
    is_stale BOOLEAN DEFAULT FALSE,
    anomaly_flags INTEGER DEFAULT 0,
    raw_data JSONB,
    
    CONSTRAINT ticks_price_check CHECK (last_price > 0)
);

-- Create hypertable if TimescaleDB is available
DO $$
BEGIN
    PERFORM create_hypertable('ticks', 'timestamp', if_not_exists => TRUE, chunk_time_interval => INTERVAL '1 day');
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Could not create hypertable for ticks';
END $$;

-- Create indexes for ticks
CREATE INDEX IF NOT EXISTS idx_ticks_symbol_timestamp ON ticks (symbol, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_ticks_timestamp ON ticks (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_ticks_feed_source ON ticks (feed_source);
CREATE INDEX IF NOT EXISTS idx_ticks_received_at ON ticks (received_at DESC);

-- OHLCV bars (candlestick data)
CREATE TABLE IF NOT EXISTS bars (
    id BIGSERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    interval_seconds INTEGER NOT NULL DEFAULT 60,
    open DECIMAL(18, 8) NOT NULL,
    high DECIMAL(18, 8) NOT NULL,
    low DECIMAL(18, 8) NOT NULL,
    close DECIMAL(18, 8) NOT NULL,
    volume BIGINT NOT NULL DEFAULT 0,
    vwap DECIMAL(18, 8),
    trades_count INTEGER,
    source VARCHAR(20) DEFAULT 'aggregated',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT bars_price_check CHECK (high >= low AND high >= open AND high >= close),
    CONSTRAINT bars_volume_check CHECK (volume >= 0),
    CONSTRAINT bars_interval_check CHECK (interval_seconds > 0),
    UNIQUE (symbol, timestamp, interval_seconds)
);

-- Create hypertable if TimescaleDB is available
DO $$
BEGIN
    PERFORM create_hypertable('bars', 'timestamp', if_not_exists => TRUE, chunk_time_interval => INTERVAL '7 days');
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Could not create hypertable for bars';
END $$;

-- Create indexes for bars
CREATE INDEX IF NOT EXISTS idx_bars_symbol_timestamp ON bars (symbol, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_bars_interval ON bars (interval_seconds);

-- -----------------------------------------------------------------------------
-- Trading Signal Tables
-- -----------------------------------------------------------------------------

-- Trading signals generated by strategies
CREATE TABLE IF NOT EXISTS signals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(20) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    signal_type VARCHAR(20) NOT NULL CHECK (signal_type IN ('BUY', 'SELL', 'HOLD', 'EXIT')),
    strategy_name VARCHAR(100) NOT NULL,
    strategy_version VARCHAR(20),
    confidence DECIMAL(5, 4) CHECK (confidence >= 0 AND confidence <= 1),
    price_at_signal DECIMAL(18, 8),
    expected_entry DECIMAL(18, 8),
    expected_exit DECIMAL(18, 8),
    stop_loss DECIMAL(18, 8),
    take_profit DECIMAL(18, 8),
    position_size INTEGER,
    time_in_force VARCHAR(20) DEFAULT 'GTC',
    metadata JSONB,
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'executed', 'expired', 'cancelled')),
    executed_at TIMESTAMPTZ,
    order_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_signals_symbol_timestamp ON signals (symbol, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_signals_strategy ON signals (strategy_name, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_signals_status ON signals (status);
CREATE INDEX IF NOT EXISTS idx_signals_signal_type ON signals (signal_type);

-- -----------------------------------------------------------------------------
-- Order Management Tables
-- -----------------------------------------------------------------------------

-- Orders placed by the system
CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    external_order_id VARCHAR(100),
    symbol VARCHAR(20) NOT NULL,
    side VARCHAR(10) NOT NULL CHECK (side IN ('BUY', 'SELL')),
    order_type VARCHAR(20) NOT NULL CHECK (order_type IN ('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', 'TRAILING_STOP')),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    filled_quantity INTEGER NOT NULL DEFAULT 0 CHECK (filled_quantity >= 0),
    remaining_quantity INTEGER GENERATED ALWAYS AS (quantity - filled_quantity) STORED,
    price DECIMAL(18, 8),
    stop_price DECIMAL(18, 8),
    time_in_force VARCHAR(10) DEFAULT 'GTC' CHECK (time_in_force IN ('GTC', 'IOC', 'FOK', 'DAY', 'GTD')),
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'submitted', 'partially_filled', 'filled', 'cancelled', 'rejected', 'expired')),
    exchange VARCHAR(20),
    account_id VARCHAR(50),
    signal_id UUID REFERENCES signals(id) ON DELETE SET NULL,
    parent_order_id UUID REFERENCES orders(id) ON DELETE SET NULL,
    is_oco BOOLEAN DEFAULT FALSE,
    oco_group_id UUID,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    submitted_at TIMESTAMPTZ,
    filled_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    rejected_at TIMESTAMPTZ,
    reject_reason TEXT,
    expires_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB
);

CREATE INDEX IF NOT EXISTS idx_orders_symbol_status ON orders (symbol, status);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_external_id ON orders (external_order_id);
CREATE INDEX IF NOT EXISTS idx_orders_signal_id ON orders (signal_id);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at DESC);

-- Order fills/executions
CREATE TABLE IF NOT EXISTS fills (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    external_fill_id VARCHAR(100),
    symbol VARCHAR(20) NOT NULL,
    side VARCHAR(10) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    price DECIMAL(18, 8) NOT NULL,
    commission DECIMAL(18, 8) DEFAULT 0,
    commission_currency VARCHAR(10) DEFAULT 'USD',
    exchange VARCHAR(20),
    liquidity VARCHAR(10) CHECK (liquidity IN ('maker', 'taker')),
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    metadata JSONB
);

CREATE INDEX IF NOT EXISTS idx_fills_order_id ON fills (order_id);
CREATE INDEX IF NOT EXISTS idx_fills_symbol_timestamp ON fills (symbol, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_fills_timestamp ON fills (timestamp DESC);

-- -----------------------------------------------------------------------------
-- Position Management Tables
-- -----------------------------------------------------------------------------

-- Current positions
CREATE TABLE IF NOT EXISTS positions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(20) NOT NULL UNIQUE,
    side VARCHAR(10) NOT NULL CHECK (side IN ('LONG', 'SHORT', 'FLAT')),
    quantity INTEGER NOT NULL DEFAULT 0,
    average_entry_price DECIMAL(18, 8),
    current_price DECIMAL(18, 8),
    unrealized_pnl DECIMAL(18, 2) DEFAULT 0,
    realized_pnl DECIMAL(18, 2) DEFAULT 0,
    total_pnl DECIMAL(18, 2) GENERATED ALWAYS AS (unrealized_pnl + realized_pnl) STORED,
    margin_used DECIMAL(18, 2) DEFAULT 0,
    opened_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_fill_id UUID REFERENCES fills(id),
    metadata JSONB
);

CREATE INDEX IF NOT EXISTS idx_positions_symbol ON positions (symbol);
CREATE INDEX IF NOT EXISTS idx_positions_side ON positions (side);

-- Position history (closed positions)
CREATE TABLE IF NOT EXISTS position_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    symbol VARCHAR(20) NOT NULL,
    side VARCHAR(10) NOT NULL,
    entry_quantity INTEGER NOT NULL,
    exit_quantity INTEGER NOT NULL,
    average_entry_price DECIMAL(18, 8) NOT NULL,
    average_exit_price DECIMAL(18, 8) NOT NULL,
    realized_pnl DECIMAL(18, 2) NOT NULL,
    commission_paid DECIMAL(18, 2) DEFAULT 0,
    opened_at TIMESTAMPTZ NOT NULL,
    closed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    duration_seconds INTEGER GENERATED ALWAYS AS (EXTRACT(EPOCH FROM (closed_at - opened_at))) STORED,
    entry_order_ids UUID[],
    exit_order_ids UUID[],
    metadata JSONB
);

CREATE INDEX IF NOT EXISTS idx_position_history_symbol ON position_history (symbol);
CREATE INDEX IF NOT EXISTS idx_position_history_closed_at ON position_history (closed_at DESC);

-- -----------------------------------------------------------------------------
-- Risk Management Tables
-- -----------------------------------------------------------------------------

-- Risk events and violations
CREATE TABLE IF NOT EXISTS risk_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_type VARCHAR(50) NOT NULL CHECK (event_type IN ('position_limit', 'daily_loss', 'drawdown', 'order_rate', 'margin_call', 'kill_switch', 'manual_override')),
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('info', 'warning', 'critical', 'emergency')),
    symbol VARCHAR(20),
    description TEXT NOT NULL,
    triggered_value DECIMAL(18, 8),
    limit_value DECIMAL(18, 8),
    action_taken VARCHAR(100),
    acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_by VARCHAR(100),
    acknowledged_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_risk_events_type ON risk_events (event_type);
CREATE INDEX IF NOT EXISTS idx_risk_events_severity ON risk_events (severity);
CREATE INDEX IF NOT EXISTS idx_risk_events_created_at ON risk_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_risk_events_acknowledged ON risk_events (acknowledged);

-- Daily P&L tracking for risk management
CREATE TABLE IF NOT EXISTS daily_pnl (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    date DATE NOT NULL UNIQUE,
    starting_equity DECIMAL(18, 2) NOT NULL,
    ending_equity DECIMAL(18, 2),
    realized_pnl DECIMAL(18, 2) DEFAULT 0,
    unrealized_pnl DECIMAL(18, 2) DEFAULT 0,
    commission_paid DECIMAL(18, 2) DEFAULT 0,
    total_pnl DECIMAL(18, 2) GENERATED ALWAYS AS (realized_pnl + unrealized_pnl - commission_paid) STORED,
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    max_drawdown_pct DECIMAL(8, 4),
    max_drawdown_amount DECIMAL(18, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_daily_pnl_date ON daily_pnl (date);

-- -----------------------------------------------------------------------------
-- System Event Tables
-- -----------------------------------------------------------------------------

-- System events and audit log
CREATE TABLE IF NOT EXISTS system_events (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_type VARCHAR(50) NOT NULL,
    component VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'info' CHECK (severity IN ('debug', 'info', 'warning', 'error', 'critical')),
    message TEXT NOT NULL,
    details JSONB,
    correlation_id VARCHAR(100),
    source_ip INET,
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_system_events_type ON system_events (event_type);
CREATE INDEX IF NOT EXISTS idx_system_events_component ON system_events (component);
CREATE INDEX IF NOT EXISTS idx_system_events_severity ON system_events (severity);
CREATE INDEX IF NOT EXISTS idx_system_events_created_at ON system_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_events_correlation ON system_events (correlation_id);

-- -----------------------------------------------------------------------------
-- Event Calendar Tables
-- -----------------------------------------------------------------------------

-- Economic events and news that may impact trading
CREATE TABLE IF NOT EXISTS event_calendar (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_name VARCHAR(200) NOT NULL,
    event_type VARCHAR(50) NOT NULL CHECK (event_type IN ('economic', 'earnings', 'dividend', 'split', 'holiday', 'fed_meeting', 'oil_report', 'inventory')),
    symbol VARCHAR(20),
    event_time TIMESTAMPTZ NOT NULL,
    timezone VARCHAR(50) DEFAULT 'America/New_York',
    importance VARCHAR(20) DEFAULT 'medium' CHECK (importance IN ('low', 'medium', 'high', 'critical')),
    forecast_value VARCHAR(100),
    actual_value VARCHAR(100),
    previous_value VARCHAR(100),
    unit VARCHAR(50),
    country VARCHAR(100),
    description TEXT,
    source VARCHAR(100),
    is_released BOOLEAN DEFAULT FALSE,
    released_at TIMESTAMPTZ,
    impact_score INTEGER CHECK (impact_score >= 0 AND impact_score <= 100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_event_calendar_time ON event_calendar (event_time);
CREATE INDEX IF NOT EXISTS idx_event_calendar_symbol ON event_calendar (symbol);
CREATE INDEX IF NOT EXISTS idx_event_calendar_type ON event_calendar (event_type);
CREATE INDEX IF NOT EXISTS idx_event_calendar_importance ON event_calendar (importance);

-- -----------------------------------------------------------------------------
-- Feed Anomaly Tables
-- -----------------------------------------------------------------------------

-- Market data feed anomalies and quality issues
CREATE TABLE IF NOT EXISTS feed_anomalies (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    feed_source VARCHAR(50) NOT NULL,
    symbol VARCHAR(20),
    anomaly_type VARCHAR(50) NOT NULL CHECK (anomaly_type IN ('stale_data', 'price_spike', 'volume_spike', 'bid_ask_inversion', 'gap', 'duplicate', 'missing', 'corrupt')),
    severity VARCHAR(20) NOT NULL DEFAULT 'warning' CHECK (severity IN ('info', 'warning', 'critical')),
    description TEXT NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    affected_ticks BIGINT[],
    raw_data_sample JSONB,
    resolution_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_feed_anomalies_source ON feed_anomalies (feed_source);
CREATE INDEX IF NOT EXISTS idx_feed_anomalies_type ON feed_anomalies (anomaly_type);
CREATE INDEX IF NOT EXISTS idx_feed_anomalies_detected ON feed_anomalies (detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_feed_anomalies_resolved ON feed_anomalies (resolved_at) WHERE resolved_at IS NULL;

-- =============================================================================
-- Views
-- =============================================================================

-- Current position summary view
CREATE OR REPLACE VIEW position_summary AS
SELECT 
    symbol,
    side,
    quantity,
    average_entry_price,
    current_price,
    unrealized_pnl,
    realized_pnl,
    total_pnl,
    ROUND((current_price - average_entry_price) / NULLIF(average_entry_price, 0) * 100, 4) as pnl_pct,
    updated_at
FROM positions
WHERE side != 'FLAT';

-- Open orders view
CREATE OR REPLACE VIEW open_orders AS
SELECT 
    o.*,
    s.signal_type as parent_signal_type,
    s.confidence as parent_signal_confidence
FROM orders o
LEFT JOIN signals s ON o.signal_id = s.id
WHERE o.status IN ('pending', 'submitted', 'partially_filled');

-- Daily trading summary view
CREATE OR REPLACE VIEW daily_trading_summary AS
SELECT 
    date,
    starting_equity,
    ending_equity,
    total_pnl,
    total_trades,
    winning_trades,
    losing_trades,
    CASE 
        WHEN total_trades > 0 THEN ROUND(winning_trades::numeric / total_trades * 100, 2)
        ELSE 0 
    END as win_rate_pct,
    max_drawdown_pct,
    max_drawdown_amount
FROM daily_pnl
ORDER BY date DESC;

-- =============================================================================
-- Functions and Triggers
-- =============================================================================

-- Update timestamp trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply update trigger to tables with updated_at column
DO $$
DECLARE
    tbl RECORD;
BEGIN
    FOR tbl IN 
        SELECT table_name 
        FROM information_schema.columns 
        WHERE column_name = 'updated_at' 
        AND table_schema = 'public'
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS update_%I_updated_at ON %I', tbl.table_name, tbl.table_name);
        EXECUTE format('
            CREATE TRIGGER update_%I_updated_at
            BEFORE UPDATE ON %I
            FOR EACH ROW
            EXECUTE FUNCTION update_updated_at_column()
        ', tbl.table_name, tbl.table_name);
    END LOOP;
END $$;

-- Function to calculate position P&L
CREATE OR REPLACE FUNCTION calculate_position_pnl(
    p_symbol VARCHAR(20),
    p_current_price DECIMAL(18, 8)
) RETURNS TABLE (
    unrealized_pnl DECIMAL(18, 2),
    realized_pnl DECIMAL(18, 2),
    total_pnl DECIMAL(18, 2)
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        CASE 
            WHEN p.side = 'LONG' THEN (p_current_price - p.average_entry_price) * p.quantity
            WHEN p.side = 'SHORT' THEN (p.average_entry_price - p_current_price) * p.quantity
            ELSE 0
        END as unrealized_pnl,
        p.realized_pnl,
        CASE 
            WHEN p.side = 'LONG' THEN (p_current_price - p.average_entry_price) * p.quantity + p.realized_pnl
            WHEN p.side = 'SHORT' THEN (p.average_entry_price - p_current_price) * p.quantity + p.realized_pnl
            ELSE p.realized_pnl
        END as total_pnl
    FROM positions p
    WHERE p.symbol = p_symbol;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- Initial Data
-- =============================================================================

-- Insert initial system event
INSERT INTO system_events (event_type, component, severity, message, details)
VALUES ('database_init', 'migrations', 'info', 'Database schema initialized', '{"version": "0.1.0"}')
ON CONFLICT DO NOTHING;

-- =============================================================================
-- Comments
-- =============================================================================

COMMENT ON TABLE ticks IS 'Raw market tick data with optional TimescaleDB hypertable';
COMMENT ON TABLE bars IS 'Aggregated OHLCV candlestick data';
COMMENT ON TABLE signals IS 'Trading signals generated by strategies';
COMMENT ON TABLE orders IS 'Order management and tracking';
COMMENT ON TABLE fills IS 'Individual order fills/executions';
COMMENT ON TABLE positions IS 'Current open positions';
COMMENT ON TABLE position_history IS 'Historical closed positions';
COMMENT ON TABLE risk_events IS 'Risk management events and violations';
COMMENT ON TABLE daily_pnl IS 'Daily profit and loss tracking';
COMMENT ON TABLE system_events IS 'System events and audit log';
COMMENT ON TABLE event_calendar IS 'Economic events and market-moving news';
COMMENT ON TABLE feed_anomalies IS 'Market data feed quality issues';
